image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm install -g snyk
          - npm install snyk-to-html -g #install snyk to html to see the report
          - snyk test --json | snyk-to-html -o result.html #Vulnerability snapshot saved at result.html
          - snyk container test node:14.1.0 --json | snyk-to-html -o result-container.html # provide the base image name to get base image vuln and remediation details;Vulnerability snapshot saved at result-container.html
          - snyk iac test # fail build on IAC misconfigurations
        artifacts:
          download: true
          paths:
            - result.html
            - result-container.html