image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm install -g snyk
          - npm install snyk-to-html -g #install snyk to html to see the report
          - snyk test --json | snyk-to-html -o result.html #Vulnerability snapshot saved at result.html

        artifacts:
          download: true
          paths:
            - result.html